site_name: Recon4IMD SPARQL Course
nav:
    - Home: index.md
    - Pre-course preparations: precourse.md
    - Course schedule: course_schedule.md
    - RDF basic concepts: concepts.md
    - GraphDB demo: demo.md
    - Music example: music.md
    - GBA1 turtle: gba1_ttl.md
    - GBA1 example: gba1.md
    - Other SPARQL interfaces: other_interfaces.md
    - RDF a bit more advanced concepts: concepts_2.md
    - Interesting SPARQL endpoint resources: interesting_endpoints.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg

# Repository
repo_name: sib-swiss/SPARQL_course
repo_url: https://github.com/sib-swiss/SPARQL_course

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
